#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Regenerate every asset the demo site (demo/) references, from repo code only.

One command, no hand-edited numbers:

    python make_demo_assets.py [--allow-missing-eprocess]

Everything the site displays is produced here and logged, with the exact
command line that produced it, into demo/assets/provenance.json. If a number
cannot be regenerated by this script, it must not appear on the site
(enforced by check_site.py).

Labels (fixed vocabulary, see D3 in the demo plan):
  - "simulated channel"                     channel.py outputs
  - "real capture (single dry-run print)"   received.jpeg / control_received.jpeg
  - "Monte Carlo simulation of the accusation statistic"  eprocess trajectories
  - "analytic (metrics.py)"                 tier table / curves
"""
import argparse
import datetime
import inspect
import json
import os
import re
import subprocess
import sys

import numpy as np
from PIL import Image

REPO = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.join(REPO, "demo", "assets")
PY = sys.executable

LABEL_SIM = "simulated channel"
LABEL_REAL = "real capture (single dry-run print)"
LABEL_MC = "Monte Carlo simulation of the accusation statistic"
LABEL_ANALYTIC = "analytic (metrics.py)"

ENTRIES = []      # provenance: every command run, with stdout
NUMBERS = {}      # every scalar the site may display, keyed


def run(cmd, label, entry_id, cwd=REPO, check=True):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    ENTRIES.append({"id": entry_id, "label": label,
                    "cmd": " ".join(str(c) for c in cmd),
                    "cwd": os.path.relpath(cwd, REPO) or ".",
                    "returncode": r.returncode,
                    "stdout": r.stdout, "stderr": r.stderr})
    if check and r.returncode != 0:
        print(r.stdout)
        print(r.stderr)
        sys.exit(f"FAILED ({entry_id}): {' '.join(str(c) for c in cmd)}")
    return r.stdout


def parse_decode(stdout):
    """Parse decode.py / run_robust.py stdout into a scalar dict."""
    out = {}
    m = re.search(r"deskew ([+-]?[\d.]+)", stdout)
    if m:
        out["deskew_deg"] = float(m.group(1))
    m = re.search(r"line-shift\s*:\s*(\d+)/(\d+)\s*=\s*([\d.]+|nan)", stdout)
    if m:
        out["line_ok"], out["line_tot"] = int(m.group(1)), int(m.group(2))
        out["line_acc"] = None if m.group(3) == "nan" else float(m.group(3))
    m = re.search(r"word-shift\s*:\s*(\d+)/(\d+)\s*=?\s*([\d.]+|nan)?.*?\((\d+) erasures\)",
                  stdout)
    if m:
        out["word_ok"], out["word_tot"] = int(m.group(1)), int(m.group(2))
        out["word_acc"] = (None if m.group(3) in (None, "nan")
                           else float(m.group(3)))
        out["erasures"] = int(m.group(4))
    m = re.search(r"payload\s*:\s*(\d+)/(\d+)", stdout)
    if m:
        out["payload_ok"], out["payload_tot"] = int(m.group(1)), int(m.group(2))
    m = re.search(r"GO/NO-GO\s*:\s*(GO|NO-GO)", stdout)
    if m:
        out["gate"] = m.group(1)
    out["aborted"] = "LINE COUNT MISMATCH" in stdout
    return out


def save_web(src, dst, long_side=1200, quality=88):
    img = Image.open(src)
    s = long_side / max(img.size)
    if s < 1.0:
        img = img.resize((round(img.width * s), round(img.height * s)),
                         Image.LANCZOS)
    if dst.lower().endswith(".jpg"):
        img.convert("L").save(dst, quality=quality)
    else:
        img.convert("L").save(dst)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--allow-missing-eprocess", action="store_true",
                    help="build everything except the Act 4 e-process assets "
                         "(exit 0 with a loud PENDING warning)")
    args = ap.parse_args()
    os.makedirs(ASSETS, exist_ok=True)
    sys.path.insert(0, REPO)

    a = lambda *p: os.path.join(ASSETS, *p)

    # ---- 1. Renders (marked + unmarked control) --------------------------------
    run([PY, os.path.join(REPO, "encode.py"), "--out", a("marked.png"),
         "--meta", a("meta.json"), "--seed", "42"],
        LABEL_ANALYTIC, "encode_marked")
    run([PY, os.path.join(REPO, "encode.py"), "--out", a("control.png"),
         "--meta", a("control_meta.json"), "--unmarked"],
        LABEL_ANALYTIC, "encode_control")

    enc = next(e for e in ENTRIES if e["id"] == "encode_marked")
    m = re.search(r"(\d+) lines, (\d+) line bits, (\d+) word bits, "
                  r"payload (\d+) bits", enc["stdout"])
    NUMBERS.update({"page_lines": int(m.group(1)),
                    "page_line_bits": int(m.group(2)),
                    "page_word_bits": int(m.group(3)),
                    "payload_bits": int(m.group(4))})

    # ---- 2. Synthetic channel presets (marked and control) ---------------------
    # Presets follow the smoke-test README recipes; every parameter is recorded
    # in the command line below.
    channel = os.path.join(REPO, "channel.py")
    presets = {
        "wa": [["--rot", "0.4", "--persp", "0.004", "--blur", "1.0",
                "--longside", "1600", "--quality", "78"]],
        "double": [["--rot", "0.8", "--persp", "0.006", "--blur", "1.2",
                    "--longside", "1600", "--quality", "74"],
                   ["--rot", "0.0", "--persp", "0.0", "--blur", "0.3",
                    "--longside", "1600", "--quality", "70"]],
        "harsh": [["--rot", "1.5", "--persp", "0.004", "--blur", "1.8",
                   "--longside", "1200", "--quality", "65"]],
    }
    variants = {}   # (preset, doc) -> image path
    for doc in ("marked", "control"):
        variants[("clean", doc)] = a(f"{doc}.png")
        for name, hops in presets.items():
            src = a(f"{doc}.png")
            for hi, hop in enumerate(hops):
                dst = a(f"ch_{name}_{doc}.jpg" if hi == len(hops) - 1
                        else f"ch_{name}_{doc}_hop{hi}.jpg")
                run([PY, channel, "--in", src, "--out", dst] + hop,
                    LABEL_SIM, f"channel_{name}_{doc}_hop{hi}")
                src = dst
            variants[(name, doc)] = src

    # ---- 3. Blind decodes of every variant, marked AND control -----------------
    decode = os.path.join(REPO, "decode.py")
    for (name, doc), img in variants.items():
        jpath = a(f"dec_{name}_{doc}.json")
        if os.path.exists(jpath):
            os.remove(jpath)
        stdout = run([PY, decode, "--img", img, "--meta", a("meta.json"),
                      "--json", jpath],
                     LABEL_SIM, f"decode_{name}_{doc}")
        parsed = parse_decode(stdout)
        rec = json.load(open(jpath)) if os.path.exists(jpath) else {}
        rec.update(parsed)
        rec.update({"variant": name, "doc": doc, "label": LABEL_SIM,
                    "entry_id": f"decode_{name}_{doc}",
                    "image": os.path.basename(img)})
        json.dump(rec, open(jpath, "w"), indent=1)
        for k in ("line_acc", "word_acc", "line_ok", "line_tot", "word_ok",
                  "word_tot", "payload_ok", "payload_tot", "erasures"):
            if rec.get(k) is not None:
                NUMBERS[f"{name}_{doc}_{k}"] = rec[k]

    # ---- 4. The real capture pair (single dry-run print) -----------------------
    robust = os.path.join(REPO, "robust_decode", "run_robust.py")
    real = {}
    for key, img in (("marked", "received.jpeg"),
                     ("control", "control_received.jpeg")):
        stdout = run([PY, robust, "--img", os.path.join(REPO, img),
                      "--meta", os.path.join(REPO, "meta.json")],
                     LABEL_REAL, f"real_{key}", cwd=ASSETS)
        real[key] = parse_decode(stdout)
        real[key]["source_image"] = img
        for k, v in real[key].items():
            if isinstance(v, (int, float)) and v is not None:
                NUMBERS[f"real_{key}_{k}"] = v
    real["label"] = LABEL_REAL
    real["note"] = ("One physical dry-run print, photographed hand-held, one "
                    "WhatsApp hop, full-page framing. Word-shift sits below "
                    "the resolution floor at this framing; line-shift is the "
                    "surviving carrier.")
    json.dump(real, open(a("real_capture.json"), "w"), indent=1)
    save_web(os.path.join(REPO, "received.jpeg"), a("real_received_web.jpg"))
    save_web(os.path.join(REPO, "control_received.jpeg"),
             a("real_control_web.jpg"))

    # ---- 5. Web-size page images, zoom crops, difference map -------------------
    save_web(a("marked.png"), a("marked_web.png"))
    save_web(a("control.png"), a("control_web.png"))

    mk = np.asarray(Image.open(a("marked.png")).convert("L"), dtype=np.int16)
    ct = np.asarray(Image.open(a("control.png")).convert("L"), dtype=np.int16)
    # Zoom window: covers the first line triplet (its middle line is marked)
    # plus enough words to show shifted gaps. Geometry from encode.py layout.
    y0, y1, x0, x1 = 300, 480, 300, 1050
    for name, arr in (("zoom_marked", mk), ("zoom_control", ct)):
        crop = Image.fromarray(arr[y0:y1, x0:x1].astype(np.uint8))
        crop = crop.resize((crop.width * 3, crop.height * 3), Image.NEAREST)
        crop.save(a(f"{name}.png"))
    diff = np.abs(mk - ct).astype(np.uint8)
    h, w = diff.shape
    rgb = np.zeros((h, w, 3), np.uint8)
    rgb[..., 0], rgb[..., 1], rgb[..., 2] = 12, 20, 36          # navy base
    mask = diff > 24
    inten = (diff[mask].astype(np.float32) / 255.0)[:, None]
    gold = np.array([201, 162, 39], np.float32)
    navy = np.array([12, 20, 36], np.float32)
    rgb[mask] = (navy + (gold - navy) * np.clip(inten * 3, 0, 1)).astype(np.uint8)
    d = Image.fromarray(rgb)
    d = d.resize((1200, round(h * 1200 / w)), Image.LANCZOS)
    d.save(a("diff_map.png"))
    ENTRIES.append({"id": "diff_map", "label": LABEL_ANALYTIC,
                    "cmd": "pixelwise |marked.png - control.png|, gold where "
                           "the renders differ (threshold 24/255)",
                    "cwd": ".", "returncode": 0, "stdout": "", "stderr": ""})

    # ---- 6. Corrected tier table + constants (metrics.py) ----------------------
    import metrics
    rows, md = metrics.build_table()
    tiers = {"label": LABEL_ANALYTIC,
             "n": metrics.TABLE_N, "budget": metrics.TABLE_BUDGET,
             "total_budget": 1e-6, "ledger_split": 5e-7,
             "rows": rows, "markdown": md,
             "correction_source": inspect.getsource(metrics.drift_factor),
             "correction_note": ("The v0.2/v0.3 cells used the erasure factor "
                                 "(1 - p) on a flip channel. The corrected "
                                 "hard-decision factor is (1 - 2p): a flipped "
                                 "symbol costs a lost vote plus an adverse "
                                 "vote. See stage0/stage0-soundness.md "
                                 "Section 4 and metrics.py drift_factor().")}
    json.dump(tiers, open(a("tiers.json"), "w"), indent=1)
    ENTRIES.append({"id": "tiers", "label": LABEL_ANALYTIC,
                    "cmd": "python -c \"import metrics; metrics.build_table()\""
                           " (n=%d, budget=%g)" % (metrics.TABLE_N,
                                                   metrics.TABLE_BUDGET),
                    "cwd": ".", "returncode": 0, "stdout": md, "stderr": ""})
    for r in rows:
        base = re.sub(r"[^a-z0-9]+", "_", r["name"])
        for col in ("flip_0.5", "flip_0.9", "erasure_0.5", "erasure_0.9"):
            NUMBERS[f"tier_{base}_{col}"] = r[col]
        NUMBERS[f"tier_{base}_c"] = r["c"]
        NUMBERS[f"tier_{base}_k"] = r["k"]

    # metrics.py locked-number self-test, recorded for the methodology note.
    run([PY, os.path.join(REPO, "test_metrics.py")],
        LABEL_ANALYTIC, "test_metrics")

    # ---- 7. Evidence-vs-symbols curve (secondary Act 4 panel) ------------------
    C, N, BUD, P = 5, metrics.TABLE_N, metrics.TABLE_BUDGET, 0.10
    ks = np.unique(np.geomspace(10, 8000, 60).astype(int))
    curve = {"label": LABEL_ANALYTIC, "c": C, "n": N, "budget": BUD,
             "p": P, "p_semantics": "flip", "beta": 0.5,
             "k": ks.tolist(),
             "epsilon1": [metrics.epsilon1(C, int(k), P, N, "flip", 0.5)
                          for k in ks],
             "tier_bounds": {"courtroom": BUD, "strong lead": 1e-3,
                             "weak lead": 5e-2}}
    json.dump(curve, open(a("evidence_curve.json"), "w"), indent=1)
    ENTRIES.append({"id": "evidence_curve", "label": LABEL_ANALYTIC,
                    "cmd": ("metrics.epsilon1(c=%d, k, p=%.2f, n=%d, 'flip', "
                            "beta=0.5) for k in geomspace(10, 8000)"
                            % (C, P, N)),
                    "cwd": ".", "returncode": 0, "stdout": "", "stderr": ""})

    # ---- 8. E-process trajectories (Act 4 primary element) ---------------------
    # Supplied module, statistical core must not be modified (decision D1c).
    # Self-test runs first and its full output is recorded in provenance
    # before any trajectory is used.
    ep_path = os.path.join(REPO, "stage0", "eprocess.py")
    ep_ok = False
    if os.path.exists(ep_path):
        st = run([PY, ep_path], LABEL_MC, "eprocess_selftest")
        verify_eprocess_selftest(st)
        import stage0.eprocess as ep
        traj = generate_eprocess_trajectories(ep)
        traj["label"] = LABEL_MC
        traj["selftest_entry"] = "eprocess_selftest"
        json.dump(traj, open(a("eprocess_trajectories.json"), "w"), indent=1)
        NUMBERS.update({"ep_alpha": traj["alpha"], "ep_bar": traj["bar"],
                        "ep_flip_p": traj["flip_p"],
                        "ep_n_symbols": traj["n_symbols"]})
        m = re.search(r"Innocent over (\S+) drips", st)
        NUMBERS["ep_selftest_innocent_n"] = float(m.group(1).replace("e", "E"))
        m = re.search(r"max e-value ([\d.e+]+)", st)
        NUMBERS["ep_selftest_max_innocent"] = float(m.group(1))
        m = re.search(r"detected ([\d.]+)%, median symbols to accuse (\d+)", st)
        NUMBERS["ep_detected_pct"] = float(m.group(1))
        NUMBERS["ep_median_symbols"] = int(m.group(2))
        ep_ok = True
    else:
        print("!" * 70)
        print("PENDING: stage0/eprocess.py not present. Act 4 e-process assets "
              "NOT built; the site's e-process panel will not render and "
              "check_site.py will fail until the file is supplied and this "
              "script is re-run.")
        print("!" * 70)
        if not args.allow_missing_eprocess:
            sys.exit(2)

    # ---- 9. Constants and GO-gate thresholds (code-derived, not hand-typed) ----
    import encode
    NUMBERS.update({
        "const_dpi": encode.DPI, "const_word_shift_px": encode.WORD_SHIFT,
        "const_line_shift_px": encode.LINE_SHIFT, "const_pitch_px": encode.PITCH,
        "const_gap_px": encode.GAP,
        "go_word_thresh": 0.85, "go_line_thresh": 0.90, "nogo_thresh": 0.60,
        "chance_level": 0.5,
        "budget_total": 1e-6, "budget_split": 5e-7,
        "tier_n": metrics.TABLE_N,
    })
    dsrc = open(os.path.join(REPO, "decode.py"), encoding="utf-8").read()
    assert "word_acc >= 0.85" in dsrc and "line_acc >= 0.90" in dsrc, \
        "GO-gate thresholds drifted from decode.py; update NUMBERS"

    prov = {"generated_utc":
            datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "labels": {"simulated": LABEL_SIM, "real": LABEL_REAL,
                       "monte_carlo": LABEL_MC, "analytic": LABEL_ANALYTIC},
            "eprocess_built": ep_ok,
            "numbers": NUMBERS,
            "entries": ENTRIES}
    json.dump(prov, open(a("provenance.json"), "w"), indent=1)
    print(f"\nwrote {len(ENTRIES)} provenance entries, "
          f"{len(NUMBERS)} numbers -> demo/assets/provenance.json")
    print("assets:", len(os.listdir(ASSETS)), "files in demo/assets/")
    if not ep_ok:
        print("REMINDER: e-process assets pending (see above).")


def verify_eprocess_selftest(stdout):
    """Guard against a drifted or corrupted eprocess.py: the supplier-stated
    reference numbers (fixed rng(0)) must reproduce at build time, or the
    build stops. Innocent ever-cross must be exactly zero; max innocent
    e-value ~9.51e4 against the 5e11 bar; guilty at flip 0.10 detected 100%
    with median 143 symbols to accuse."""
    problems = []
    m = re.search(r"ever-cross rate at 1/alpha:\s*([\d.e+-]+)", stdout)
    if not m or float(m.group(1)) != 0.0:
        problems.append(f"innocent ever-cross rate {m.group(1) if m else '?'} "
                        "(expected 0.00e+00)")
    m = re.search(r"max e-value ([\d.e+]+)", stdout)
    if not m or not (8.0e4 <= float(m.group(1)) <= 1.1e5):
        problems.append(f"max innocent e-value {m.group(1) if m else '?'} "
                        "(expected ~9.51e+04)")
    m = re.search(r"detected ([\d.]+)%, median symbols to accuse (\d+)", stdout)
    if not m or float(m.group(1)) != 100.0 or not (138 <= int(m.group(2)) <= 148):
        problems.append("guilty detection/median "
                        f"{m.group(0) if m else '?'} "
                        "(expected 100.0%, median 143)")
    if problems:
        print(stdout)
        sys.exit("STOP: eprocess.py self-test differs materially from the "
                 "supplier-verified reference:\n  " + "\n  ".join(problems))


def generate_eprocess_trajectories(ep):
    """Act 4 trajectories via the supplied stage0/eprocess.py, fixed seeds.

    Uses only the module's public API (sample_innocent / sample_guilty and
    the EProcess class) per decision D1; the statistical core is untouched.
    Operating point matches the module self-test: alpha = eta_0 = 2e-12
    (Stage 0 ledger), accusation bar 1/alpha. Guilty trajectories are
    truncated shortly after crossing so the animation focuses on the bar."""
    alpha, n_symbols, flip_p = 2e-12, 400, 0.10
    seeds = {"innocent": 101, "guilty": 201}
    out = {"alpha": alpha, "bar": 1.0 / alpha, "n_symbols": n_symbols,
           "flip_p": flip_p, "seeds": seeds, "innocent": [], "guilty": [],
           "crossed_at": []}
    U_inn = ep.sample_innocent(3, n_symbols, np.random.default_rng(seeds["innocent"]))
    U_gil = ep.sample_guilty(3, n_symbols, np.random.default_rng(seeds["guilty"]),
                             flip=flip_p)
    for row in U_inn:
        proc = ep.EProcess(alpha)
        out["innocent"].append([float(proc.update(u)) for u in row])
    for row in U_gil:
        proc = ep.EProcess(alpha)
        vals, crossed = [], None
        for u in row:
            vals.append(float(proc.update(u)))
            if crossed is None and proc.accuse():
                crossed = len(vals)
            if crossed is not None and len(vals) >= crossed + 25:
                break
        out["guilty"].append(vals)
        out["crossed_at"].append(crossed)
    return out


if __name__ == "__main__":
    main()
